# Generated by Django 5.1.2 on 2024-12-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_user_profile_picture_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_title',
            new_name='job_title_details',
        ),
        migrations.AddField(
            model_name='user',
            name='job_title_main',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
